# fly.toml app configuration file generated for calendar-backend-green-river-9863 on 2025-10-06T11:40:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'calendar-backend-green-river-9863'
primary_region = 'cdg'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/app/dist'
  url_prefix = '/'
