import createClient from "openapi-fetch";
import type { paths } from "../types/api"; // generated by openapi-typescript
import { useMutation, useQuery } from "@tanstack/react-query";

const BASE_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:3000";

const client = createClient<paths>({ baseUrl: BASE_URL });

export type Meeting =
  paths["/meetings/"]["get"]["responses"]["200"]["content"]["application/json"]["meetings"][number];

export type MeetingCreate =
  paths["/meetings/"]["post"]["requestBody"]["content"]["application/json"];

export const useMeetings = () => {
  return useQuery({
    queryKey: ["meetings"],
    queryFn: async () => {
      const { data, error } = await client.GET("/meetings/", {
        headers: {
          "Content-Type": "application/json",
        },
      });
      if (error) {
        console.error(error);
        throw error;
      }
      return data.meetings;
    },
  });
};

export const useCreateMeeting = () => {
  return useMutation({
    mutationFn: async (meeting: MeetingCreate) => {
      const { data, error } = await client.POST("/meetings/", {
        body: meeting,
      });
      if (error) {
        console.error(error);
        throw error;
      }
      return data;
    },
  });
};
