/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meetings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeetings"];
        put?: never;
        post: operations["postMeetings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        meetings: {
                            id: string;
                            /** Format: date-time */
                            startDate: string;
                            duration: number;
                        }[];
                    };
                };
            };
        };
    };
    postMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    topic: string;
                    /** Format: date-time */
                    startDate: string;
                    duration: number;
                };
                "application/x-www-form-urlencoded": {
                    topic: string;
                    /** Format: date-time */
                    startDate: string;
                    duration: number;
                };
                "multipart/form-data": {
                    topic: string;
                    /** Format: date-time */
                    startDate: string;
                    duration: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** Format: date-time */
                        startDate: string;
                        duration: number;
                        joinLink: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
}
